---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# mousetrap

Mouse-tracking, the analysis of mouse movements in computerized experiments, is a method that is becoming increasingly popular in the cognitive sciences.
The `mousetrap` package offers functions for importing, preprocessing, analyzing, aggregating, and visualizing mouse-tracking data.
An overview of the functions in this package is given in the package description, which can be accessed with `package?mousetrap` once the package has been installed.

## General Information

The `mousetrap` package was developed by Pascal Kieslich and Felix Henninger. It is published under the GNU General Public License (version 3).

## Installation
* Once `mousetrap` is available on CRAN, the current stable version can be installed via `install.packages("mousetrap")`.
* To install the latest development version from GitHub, you need the `devtools` package .
  The development version can be installed via `devtools::install_github("pascalkieslich/mousetrap@master")`.

## Acknowledgments

We thank Johanna Hepp for helpful comments on the documentation of this package and Monika Wiegelmann for testing a development version.