# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cleanAngles <- function(as) {
    .Call('mousetrap_cleanAngles', PACKAGE = 'mousetrap', as)
}

distMat <- function(x, y, power = 2L) {
    .Call('mousetrap_distMat', PACKAGE = 'mousetrap', x, y, power)
}

distMatV <- function(x, y, power = 2L) {
    .Call('mousetrap_distMatV', PACKAGE = 'mousetrap', x, y, power)
}

distMat3d <- function(x, y, z, power = 2L) {
    .Call('mousetrap_distMat3d', PACKAGE = 'mousetrap', x, y, z, power)
}

distMat3dV <- function(x, y, z, power = 2L) {
    .Call('mousetrap_distMat3dV', PACKAGE = 'mousetrap', x, y, z, power)
}

select_max <- function(x, y) {
    .Call('mousetrap_select_max', PACKAGE = 'mousetrap', x, y)
}

computeNorm <- function(r) {
    .Call('mousetrap_computeNorm', PACKAGE = 'mousetrap', r)
}

gaussBlurSlow <- function(source, target, w, h, r) {
    .Call('mousetrap_gaussBlurSlow', PACKAGE = 'mousetrap', source, target, w, h, r)
}

gaussBlur <- function(source, target, w, h, r) {
    .Call('mousetrap_gaussBlur', PACKAGE = 'mousetrap', source, target, w, h, r)
}

boxBlur <- function(source, target, w, h, r) {
    .Call('mousetrap_boxBlur', PACKAGE = 'mousetrap', source, target, w, h, r)
}

getAngleP <- function(x, y) {
    .Call('mousetrap_getAngleP', PACKAGE = 'mousetrap', x, y)
}

getAngleV <- function(x, y) {
    .Call('mousetrap_getAngleV', PACKAGE = 'mousetrap', x, y)
}

getAnglesP <- function(xs, ys) {
    .Call('mousetrap_getAnglesP', PACKAGE = 'mousetrap', xs, ys)
}

getAnglesV <- function(xs, ys) {
    .Call('mousetrap_getAnglesV', PACKAGE = 'mousetrap', xs, ys)
}

getlast <- function(trajectories) {
    .Call('mousetrap_getlast', PACKAGE = 'mousetrap', trajectories)
}

getLength <- function(x, y) {
    .Call('mousetrap_getLength', PACKAGE = 'mousetrap', x, y)
}

getLength3d <- function(x, y, z) {
    .Call('mousetrap_getLength3d', PACKAGE = 'mousetrap', x, y, z)
}

getLengths <- function(xs, ys) {
    .Call('mousetrap_getLengths', PACKAGE = 'mousetrap', xs, ys)
}

getLengths3d <- function(xs, ys, zs) {
    .Call('mousetrap_getLengths3d', PACKAGE = 'mousetrap', xs, ys, zs)
}

getVelocity <- function(x, y) {
    .Call('mousetrap_getVelocity', PACKAGE = 'mousetrap', x, y)
}

getVelocity3d <- function(x, y, z) {
    .Call('mousetrap_getVelocity3d', PACKAGE = 'mousetrap', x, y, z)
}

getVelocities <- function(xs, ys) {
    .Call('mousetrap_getVelocities', PACKAGE = 'mousetrap', xs, ys)
}

getVelocities3d <- function(xs, ys, zs) {
    .Call('mousetrap_getVelocities3d', PACKAGE = 'mousetrap', xs, ys, zs)
}

spatialize <- function(x, y, npts) {
    .Call('mousetrap_spatialize', PACKAGE = 'mousetrap', x, y, npts)
}

spatialize3d <- function(x, y, z, npts) {
    .Call('mousetrap_spatialize3d', PACKAGE = 'mousetrap', x, y, z, npts)
}

spatialize4d <- function(x, y, z1, z2, npts) {
    .Call('mousetrap_spatialize4d', PACKAGE = 'mousetrap', x, y, z1, z2, npts)
}

spatializeArray <- function(xs, ys, n_pts) {
    .Call('mousetrap_spatializeArray', PACKAGE = 'mousetrap', xs, ys, n_pts)
}

spatializeArrayToLong <- function(xs, ys, n_pts) {
    .Call('mousetrap_spatializeArrayToLong', PACKAGE = 'mousetrap', xs, ys, n_pts)
}

spatializeArray3d <- function(xs, ys, zs, n_pts) {
    .Call('mousetrap_spatializeArray3d', PACKAGE = 'mousetrap', xs, ys, zs, n_pts)
}

spatializeArrayToLong3d <- function(xs, ys, zs, n_pts) {
    .Call('mousetrap_spatializeArrayToLong3d', PACKAGE = 'mousetrap', xs, ys, zs, n_pts)
}

spatializeArrayToLong4d <- function(xs, ys, z1s, z2s, n_pts) {
    .Call('mousetrap_spatializeArrayToLong4d', PACKAGE = 'mousetrap', xs, ys, z1s, z2s, n_pts)
}

tab <- function(v1, v2) {
    .Call('mousetrap_tab', PACKAGE = 'mousetrap', v1, v2)
}

tab_sum <- function(v1, v2, a) {
    .Call('mousetrap_tab_sum', PACKAGE = 'mousetrap', v1, v2, a)
}

tab_mean <- function(v1, v2, a) {
    .Call('mousetrap_tab_mean', PACKAGE = 'mousetrap', v1, v2, a)
}

trajAlign <- function(xs, ys, start, end, coordinates) {
    .Call('mousetrap_trajAlign', PACKAGE = 'mousetrap', xs, ys, start, end, coordinates)
}

trajAlign3d <- function(xs, ys, zs, start, end, coordinates) {
    .Call('mousetrap_trajAlign3d', PACKAGE = 'mousetrap', xs, ys, zs, start, end, coordinates)
}

