# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distMat <- function(x, y, power = 2L) {
    .Call('mousetrap_distMat', PACKAGE = 'mousetrap', x, y, power)
}

distMatV <- function(x, y, power = 2L) {
    .Call('mousetrap_distMatV', PACKAGE = 'mousetrap', x, y, power)
}

distMat3d <- function(x, y, z, power = 2L) {
    .Call('mousetrap_distMat3d', PACKAGE = 'mousetrap', x, y, z, power)
}

distMat3dV <- function(x, y, z, power = 2L) {
    .Call('mousetrap_distMat3dV', PACKAGE = 'mousetrap', x, y, z, power)
}

getAngleP <- function(x, y) {
    .Call('mousetrap_getAngleP', PACKAGE = 'mousetrap', x, y)
}

getAngleV <- function(x, y) {
    .Call('mousetrap_getAngleV', PACKAGE = 'mousetrap', x, y)
}

getAnglesP <- function(xs, ys) {
    .Call('mousetrap_getAnglesP', PACKAGE = 'mousetrap', xs, ys)
}

getAnglesV <- function(xs, ys) {
    .Call('mousetrap_getAnglesV', PACKAGE = 'mousetrap', xs, ys)
}

